bug(query): Stitch must accept NaN on only one RV and not return NaN for that (#1041)
Currently, stitching returns NaN if both RVs have a sample for same instant, irrespective of whether
only one RV has NaN for that instant. This PR fixes it to pick the non-NaN value for those instants.
With this, Binary Join stitching issues seen when querying across spread change boundaries are fixed.
Side Fix: Also fixed len NoSuchMethodError caused in a previous PR